-- Mountain Social Adventure client experience v1.8
local Players=game:GetService("Players");local RS=game:GetService("ReplicatedStorage");local Lighting=game:GetService("Lighting");local UIS=game:GetService("UserInputService");local RunService=game:GetService("RunService");local TweenService=game:GetService("TweenService")
local player=Players.LocalPlayer;local remotes=RS:WaitForChild("ACC_MountainRemotes");local carryRemote=remotes:WaitForChild("Carry");local weatherRemote=remotes:WaitForChild("Weather");local photoRemote=remotes:WaitForChild("PhotoMode")
local gui=Instance.new("ScreenGui");gui.Name="ACC_MountainHUD";gui.ResetOnSpawn=false;gui.Parent=player:WaitForChild("PlayerGui")
local function button(n,text,pos)local b=Instance.new("TextButton");b.Name=n;b.Text=text;b.Size=UDim2.fromOffset(116,38);b.Position=pos;b.AnchorPoint=Vector2.new(1,1);b.BackgroundTransparency=.28;b.TextScaled=true;b.Font=Enum.Font.GothamMedium;b.Parent=gui;return b end
local carryBtn=button("CarryButton","Carry",UDim2.new(1,-16,1,-60));local dropBtn=button("DropButton","Drop",UDim2.new(1,-16,1,-16));local photoBtn=button("PhotoButton","Photo",UDim2.new(0,132,1,-16))
local status=Instance.new("TextLabel");status.Size=UDim2.fromOffset(210,30);status.Position=UDim2.new(0,14,0,14);status.BackgroundTransparency=.42;status.TextScaled=true;status.Font=Enum.Font.GothamMedium;status.Text="CLEAR • TRAIL";status.Parent=gui
local toast=Instance.new("TextLabel");toast.AnchorPoint=Vector2.new(.5,.5);toast.Position=UDim2.fromScale(.5,.22);toast.Size=UDim2.fromOffset(330,54);toast.BackgroundTransparency=1;toast.TextTransparency=1;toast.TextScaled=true;toast.Font=Enum.Font.GothamBold;toast.TextColor3=Color3.new(1,1,1);toast.Parent=gui
local function notify(text)local tw1=TweenService:Create(toast,TweenInfo.new(.35),{TextTransparency=0});toast.Text=text;tw1:Play();task.delay(2.4,function()TweenService:Create(toast,TweenInfo.new(.6),{TextTransparency=1}):Play()end)end
local function nearest(max)local c=player.Character;local r=c and c:FindFirstChild("HumanoidRootPart");if not r then return end;local best,bd;for _,p in ipairs(Players:GetPlayers())do if p~=player and p.Character and p.Character:FindFirstChild("HumanoidRootPart")then local d=(p.Character.HumanoidRootPart.Position-r.Position).Magnitude;if d<=max and(not bd or d<bd)then best,bd=p,d end end end;return best end
carryBtn.Activated:Connect(function()local t=nearest(12);if t then carryRemote:FireServer("carry",t.UserId)else notify("No hiker nearby")end end);dropBtn.Activated:Connect(function()carryRemote:FireServer("drop")end)
local photo=false;local oldFov=70;local function setPhoto(on)if on==photo then return end;photo=on;local cam=workspace.CurrentCamera;if on then oldFov=cam.FieldOfView;cam.FieldOfView=60;status.Visible=false;carryBtn.Visible=false;dropBtn.Visible=false;photoBtn.Text="Exit Photo" else cam.FieldOfView=oldFov;status.Visible=true;carryBtn.Visible=true;dropBtn.Visible=true;photoBtn.Text="Photo" end;photoRemote:FireServer(on)end;photoBtn.Activated:Connect(function()setPhoto(not photo)end)
local rain;local function ensureRain()if rain and rain.Parent then return rain end;local cam=workspace.CurrentCamera;if not cam then return end;local a=Instance.new("Attachment");a.Position=Vector3.new(0,22,-8);a.Parent=cam;local p=Instance.new("ParticleEmitter");p.Rate=0;p.Lifetime=NumberRange.new(.5,.7);p.Speed=NumberRange.new(55,68);p.EmissionDirection=Enum.NormalId.Bottom;p.SpreadAngle=Vector2.new(8,8);p.Size=NumberSequence.new(.08);p.Parent=a;rain=p;return p end
local function weather(s)s=tostring(s or"CLEAR");status.Text=s.." • "..tostring(workspace:GetAttribute("ACC_DayPhase")or"TRAIL");local p=ensureRain();if p then p.Rate=s=="RAIN" and 520 or 0 end;if s=="FOG" then notify("Fog is moving across the ridge")elseif s=="RAIN" then notify("Mountain rain incoming")end end;weatherRemote.OnClientEvent:Connect(weather);weather(workspace:GetAttribute("ACC_Weather"))
local lastCP=player:GetAttribute("ACC_Checkpoint")or 0;player:GetAttributeChangedSignal("ACC_Checkpoint"):Connect(function()local cp=player:GetAttribute("ACC_Checkpoint")or 0;if cp>lastCP then notify(cp>=12 and "SUMMIT REACHED" or ("Checkpoint "..cp.." secured"))end;lastCP=cp end)
player:GetAttributeChangedSignal("ACC_SecretFound"):Connect(function()if player:GetAttribute("ACC_SecretFound")then notify("SECRET SUMMIT DISCOVERED")end end)
UIS.InputBegan:Connect(function(i,p)if not p and i.KeyCode==Enum.KeyCode.P then setPhoto(not photo)end end)
RunService.RenderStepped:Connect(function()if rain and rain.Parent and workspace.CurrentCamera and rain.Parent.Parent~=workspace.CurrentCamera then rain.Parent.Parent=workspace.CurrentCamera end;local phase=workspace:GetAttribute("ACC_DayPhase")or"TRAIL";local w=workspace:GetAttribute("ACC_Weather")or"CLEAR";status.Text=w.." • "..phase end)