-- Mountain Social Adventure v2.0 TRAVERSAL HOTFIX
local Workspace=game:GetService("Workspace");local Lighting=game:GetService("Lighting");local Terrain=Workspace.Terrain
local ROOT_NAME="ACC_MountainSocial";local old=Workspace:FindFirstChild(ROOT_NAME);if old then old:Destroy()end
local root=Instance.new("Folder");root.Name=ROOT_NAME;root.Parent=Workspace
local folders={};for _,n in ipairs({"Checkpoints","Camps","PhotoSpots","Secrets","Decor","RouteAnchors"})do local f=Instance.new("Folder");f.Name=n;f.Parent=root;folders[n]=f end
local function part(n,s,cf,m,c,p,tr,coll)local x=Instance.new("Part");x.Name=n;x.Anchored=true;x.Size=s;x.CFrame=cf;x.Material=m or Enum.Material.Slate;if c then x.Color=c end;x.Transparency=tr or 0;x.CanCollide=coll~=false;x.TopSurface=Enum.SurfaceType.Smooth;x.BottomSurface=Enum.SurfaceType.Smooth;x.Parent=p or root;return x end
local function anchor(n,pos,p)local x=part(n,Vector3.new(10,1,10),CFrame.new(pos),Enum.Material.SmoothPlastic,Color3.fromRGB(244,186,72),p,.94,false);x:SetAttribute("ACCAnchor",true);return x end
local function trail(n,a,b,w)local d=b-a;local dist=d.Magnitude;local mid=(a+b)/2;local x=part(n,Vector3.new(w,2.2,dist),CFrame.lookAt(mid,b),Enum.Material.Ground,Color3.fromRGB(100,84,64),root,.02,true);x:SetAttribute("RouteSegment",true);return x end
Lighting.ClockTime=5.45;Lighting.Brightness=2.15;Lighting.GlobalShadows=true
local route={{"Basecamp ACC",Vector3.new(0,22,690)},{"Gerbang Hutan",Vector3.new(-132,75,555)},{"Sungai Batu",Vector3.new(88,126,430)},{"Air Terjun Lumina",Vector3.new(212,182,300)},{"Camp Rimba",Vector3.new(78,236,158)},{"Tebing Angin",Vector3.new(-118,300,34)},{"Hutan Kabut",Vector3.new(-224,356,-106)},{"Jembatan Awan",Vector3.new(-74,414,-242)},{"Camp Atas",Vector3.new(116,470,-336)},{"Ridge Batu",Vector3.new(204,526,-432)},{"Lautan Awan",Vector3.new(94,575,-540)},{"Summit ACC",Vector3.new(0,620,-650)}}
Terrain:Clear();Terrain:FillBlock(CFrame.new(0,-30,0),Vector3.new(1900,60,1900),Enum.Material.Ground)
local nodes={{Vector3.new(0,54,140),420},{Vector3.new(-72,118,65),335},{Vector3.new(84,168,-5),315},{Vector3.new(-48,228,-125),280},{Vector3.new(66,292,-245),236},{Vector3.new(-35,365,-345),198},{Vector3.new(28,445,-455),158},{Vector3.new(-12,520,-550),122},{Vector3.new(0,585,-630),84}};for _,n in ipairs(nodes)do Terrain:FillBall(n[1],n[2],Enum.Material.Rock)end
-- Wide, solid, walkable route. Earlier route parts had CanCollide=false and players fell through.
for i=1,#route-1 do local a,b=route[i][2],route[i+1][2];local dir=b-a;local side=Vector3.new(-dir.Z,0,dir.X);if side.Magnitude>0 then side=side.Unit end;local pts={a};for s=1,3 do local t=s/4;local base=a:Lerp(b,t);local sway=math.sin((i*1.7+s)*1.2)*(10+(i%3)*3);table.insert(pts,base+side*sway)end;table.insert(pts,b);for j=1,#pts-1 do trail(string.format("Trail_%02d_%02d",i,j),pts[j]-Vector3.new(0,1.5,0),pts[j+1]-Vector3.new(0,1.5,0),i<5 and 18 or 14)end end
-- Solid safety clearings under every checkpoint.
for i,info in ipairs(route)do local pos=info[2];local pad=part("TrailSafePad_"..i,Vector3.new(i==1 and 42 or 24,2,i==1 and 42 or 24),CFrame.new(pos-Vector3.new(0,1.6,0)),i<7 and Enum.Material.Ground or Enum.Material.Rock,i<7 and Color3.fromRGB(96,84,66) or Color3.fromRGB(90,91,89),root,0,true);local cp=anchor(string.format("CP%02d_%s",i,info[1]:gsub(" ","_")),pos+Vector3.new(0,1.5,0),folders.Checkpoints);cp:SetAttribute("CheckpointIndex",i);cp:SetAttribute("CheckpointName",info[1]);cp:SetAttribute("SaveReady",true)end
local spawn=Instance.new("SpawnLocation");spawn.Name="MountainSpawn";spawn.Anchored=true;spawn.Size=Vector3.new(18,1,18);spawn.CFrame=CFrame.new(route[1][2]+Vector3.new(0,1,0));spawn.Transparency=1;spawn.CanCollide=true;spawn.Neutral=true;spawn.Duration=0;spawn.Parent=root
-- Simple camps/monument retained.
for _,idx in ipairs({1,5,9})do local pos=route[idx][2];local camp=Instance.new("Model");camp.Name="Camp_"..idx;camp.Parent=folders.Camps;local fire=part("Campfire",Vector3.new(4,1,4),CFrame.new(pos+Vector3.new(15,1,8)),Enum.Material.Slate,Color3.fromRGB(72,70,66),camp,0,true);fire:SetAttribute("CampfireReady",true);local l=Instance.new("PointLight");l.Range=20;l.Brightness=1.7;l.Color=Color3.fromRGB(255,178,96);l.Parent=fire end
local summit=route[12][2];local monument=part("ACC_SummitMonument",Vector3.new(7,20,7),CFrame.new(summit+Vector3.new(0,10,-9)),Enum.Material.Granite,Color3.fromRGB(82,83,84),root,0,true);monument:SetAttribute("SummitTriggerReady",true)
local ss=anchor("SecretSummit",Vector3.new(-390,558,-600),folders.Secrets);ss:SetAttribute("SecretSummit",true);ss:SetAttribute("DiscoveryId","SECRET_TRAIL_01")
root:SetAttribute("Project","Mountain Social Adventure");root:SetAttribute("MasterPlanLocked",true);root:SetAttribute("CheckpointSaveReady",true);root:SetAttribute("MobileFriendly",true);root:SetAttribute("TraversalHotfix","2.0");root:SetAttribute("BuildVersion","2.0.0-traversal-hotfix")
print("[ACC] Mountain v2.0 solid traversal generated")