-- ACC Mountain Master v4.0 — canonical primary expedition route metadata
-- Physical trail is generated by mountain.world.server.lua. This module must not overlay duplicate roads.
local Workspace=game:GetService("Workspace")
local root=Workspace:WaitForChild("ACC_MountainSocial",20)
if not root then warn("[Mountain:v4 routes] ACC_MountainSocial missing") return end
local existing=root:FindFirstChild("MasterRoutes");if existing then existing:Destroy() end
local routesFolder=Instance.new("Folder");routesFolder.Name="MasterRoutes";routesFolder.Parent=root
local points={
 Vector3.new(-55,48,-30),Vector3.new(-180,105,-270),Vector3.new(20,165,-520),Vector3.new(185,230,-770),
 Vector3.new(42,300,-1020),Vector3.new(-185,380,-1250),Vector3.new(-265,460,-1480),Vector3.new(-78,540,-1705),
 Vector3.new(165,620,-1910),Vector3.new(265,690,-2120),Vector3.new(112,755,-2315),Vector3.new(0,820,-2525)
}
local model=Instance.new("Model");model.Name="PRIMARY_EXPEDITION_ROUTE";model.Parent=routesFolder
model:SetAttribute("RouteName","PRIMARY")
model:SetAttribute("Difficulty","PROGRESSIVE")
model:SetAttribute("StartsAt","POS1_TRAILHEAD")
model:SetAttribute("EndsAt","SUMMIT_ACC")
for i,p in ipairs(points) do
 local a=Instance.new("Part");a.Name=string.format("RouteAnchor_%02d",i);a.Anchored=true;a.Size=Vector3.new(2,2,2);a.CFrame=CFrame.new(p);a.Transparency=1;a.CanCollide=false;a.Parent=model
 a:SetAttribute("RouteIndex",i);a:SetAttribute("RouteName","PRIMARY")
end
root:SetAttribute("RouteSystem","v4.0")
root:SetAttribute("RouteCount",1)
root:SetAttribute("RoutePolicy","ONE_CLEAR_PRIMARY_ROUTE")
Workspace:SetAttribute("ACC_MountainRoutes","v3.0") -- compatibility for existing readiness gate
print("[ACC] Mountain v4 canonical route metadata ready")
