local Config = {
    ProjectId = "after-school-city",
    DisplayName = "AFTER SCHOOL CITY",
    Version = "1.0.0-gameplay-foundation-1",
    OrientationBaseVersion = "0.4.7-orientation-correction-1",
    VisualFidelityVersion = "0.5.0-visual-fidelity-1",
    RuntimeReconcileVersion = "0.5.1-runtime-reconcile-1",
    RuntimeHardCleanupVersion = "0.5.2-runtime-hard-cleanup-1",
    RoadCenterlineClearanceVersion = "0.5.3-road-centerline-clearance-1",
    PremiumExteriorVersion = "0.6.0-premium-exterior-1",
    SchoolInteriorVersion = "0.7.0-school-interior-1",
    SchoolInteriorPolishVersion = "0.7.1-school-interior-polish-1",
    SchoolVisualDepthVersion = "0.7.2-school-visual-depth-1",
    SignageOrientationHotfixVersion = "0.7.3-signage-orientation-hotfix-1",
    SchoolArchitecturalCleanupVersion = "0.7.4-school-architectural-cleanup-1",
    LockerClearanceHotfixVersion = "0.7.5-locker-clearance-hotfix-1",
    ExteriorLockerCleanupVersion = "0.7.6-exterior-locker-cleanup-1",
    SchoolRoadVisualDefectCleanupVersion = "0.7.7-school-road-visual-defect-cleanup-1",
    StudentRowShopInteriorsVersion = "0.8.0-student-row-shop-interiors-1",
    RoadConcreteStripCleanupVersion = "0.8.1-road-concrete-strip-cleanup-1",
    RoadSidewalkIntersectionCleanupVersion = "0.8.2-road-sidewalk-intersection-cleanup-1",
    GameplayFoundationVersion = "1.0.0-gameplay-foundation-1",

    Roblox = {
        UniverseId = "10745359869",
        PlaceId = "121603385909425",
    },

    World = {
        RootName = "AfterSchoolCity",
        GroundY = 0,
        Spawn = Vector3.new(0, 2.2, 157),
        DistrictTravelTargetSeconds = 45,
        Districts = {
            School = {Center = Vector3.new(0, 0, 210), Size = Vector3.new(220, 2, 150)},
            Downtown = {Center = Vector3.new(0, 0, 0), Size = Vector3.new(230, 2, 170)},
            SkatePark = {Center = Vector3.new(235, 0, 0), Size = Vector3.new(150, 2, 150)},
            Park = {Center = Vector3.new(0, 0, -210), Size = Vector3.new(220, 2, 150)},
            Residential = {Center = Vector3.new(-235, 0, 0), Size = Vector3.new(150, 2, 150)},
            SportsField = {Center = Vector3.new(235, 0, 210), Size = Vector3.new(150, 2, 130)},
        },
    },

    Gameplay = {
        StartingCoins = 250,
        StartingLifeLevel = 1,
        FirstActivityReward = 100,
        DailyMissionCount = 3,
    },

    Flags = {
        EnableBlockoutScaffold = false,
        EnablePremiumFoundation = true,
        EnableCityLifePass = true,
        EnableStreetDensityPass = true,
        EnableSpatialCleanupPass = true,
        EnableStructuralRealignmentPass = true,
        EnableLayoutCorrectionPass = true,
        EnableCirculationSanitizePass = true,
        EnableClearanceSanitizePass = true,
        EnableSourceSpatialFixPass = true,
        EnableOrientationCorrectionPass = true,
        EnableVisualFidelityPass = true,
        EnableRuntimeReconcilePass = true,
        EnableRuntimeHardCleanupPass = true,
        EnableRoadCenterlineClearancePass = true,
        EnablePremiumExteriorPass = true,
        EnableSchoolInteriorPass = true,
        EnableSchoolInteriorPolishPass = true,
        EnableSchoolVisualDepthPass = true,
        EnableSignageOrientationHotfixPass = true,
        EnableSchoolArchitecturalCleanupPass = true,
        EnableLockerClearanceHotfixPass = true,
        EnableExteriorLockerCleanupPass = true,
        EnableSchoolRoadVisualDefectCleanupPass = true,
        EnableStudentRowShopInteriorsPass = true,
        EnableRoadConcreteStripCleanupPass = true,
        EnableRoadSidewalkIntersectionCleanupPass = true,
        EnableDebugBillboards = false,
        EnableActivities = true,
        EnableEconomy = true,
        EnablePersistence = true,
        EnablePersonalRoom = false,
        EnableClubs = false,
    },
}

return Config
