const fs=require('fs');
const path=require('path');
const root=process.cwd();
const raw=(f)=>fs.readFileSync(path.join(root,f),'utf8');
const cdata=(s)=>String(s).replaceAll(']]>',']]]]><![CDATA[>');
const server=raw('maps/track-01/runtime.server.lua');
const client=raw('maps/track-01/runtime.client.lua');
const xml=`<roblox xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.roblox.com/roblox.xsd" version="4"><External>null</External><External>nil</External><Item class="Workspace" referent="W"><Properties><string name="Name">Workspace</string></Properties></Item><Item class="Lighting" referent="L"><Properties><float name="Brightness">1.65</float><double name="ClockTime">23.15</double><string name="Name">Lighting</string></Properties></Item><Item class="ServerScriptService" referent="S"><Properties><string name="Name">ServerScriptService</string></Properties><Item class="Script" referent="TS"><Properties><string name="Name">TRACK01_Runtime</string><bool name="Disabled">false</bool><ProtectedString name="Source"><![CDATA[${cdata(server)}]]></ProtectedString></Properties></Item></Item><Item class="StarterPlayer" referent="P"><Properties><string name="Name">StarterPlayer</string></Properties><Item class="StarterPlayerScripts" referent="PS"><Properties><string name="Name">StarterPlayerScripts</string></Properties><Item class="LocalScript" referent="TC"><Properties><string name="Name">TRACK01_Client</string><bool name="Disabled">false</bool><ProtectedString name="Source"><![CDATA[${cdata(client)}]]></ProtectedString></Properties></Item></Item></Item></roblox>`;
const out=path.join(root,'maps/track-01/place.rbxlx');
fs.writeFileSync(out,xml);
console.log('[TRACK 01] built',Buffer.byteLength(xml),'bytes',out);
