-- BBYA SOCIAL HUB — LEAD DANCE SYNC CLIENT v3 SLIDER
-- Sync logic preserved. UI rebuilt to avoid overlap; speed uses draggable 0.50x–1.75x slider.

local Players=game:GetService("Players")
local ReplicatedStorage=game:GetService("ReplicatedStorage")
local UserInputService=game:GetService("UserInputService")
local player=Players.LocalPlayer
local pg=player:WaitForChild("PlayerGui")
local remotes=ReplicatedStorage:WaitForChild("BBYAClubRemotes",30)
local social=remotes and remotes:WaitForChild("SocialHangout",30);if not social then return end
local leadSyncActive=false;local leadSpeed=1;local latestLeadTrack=nil;local syncTrack=nil;local originalPanel=nil;local bar=nil;local statusLabel=nil;local speedLabel=nil;local sliderFill=nil;local sliderThumb=nil;local boundAnimator=nil;local animationConn=nil;local runningConn=nil
local function isLead()return player:GetAttribute("BBYAHasLeadRole")==true and player:GetAttribute("BBYAManagedRole")=="LEAD"end
local function carryBusy()return player:GetAttribute("BBYACarryingUserId")~=nil or player:GetAttribute("BBYACarriedByUserId")~=nil end
local function humanoid()local c=player.Character;return c and c:FindFirstChildOfClass("Humanoid")end
local function animator()local h=humanoid();return h and h:FindFirstChildOfClass("Animator")end
local function clampSpeed(v)return math.clamp(tonumber(v)or 1,.50,1.75)end
local function animationId(track)if not track then return nil end;local ok,a=pcall(function()return track.Animation end);if not ok or not a then return nil end;local ok2,id=pcall(function()return a.AnimationId end);if not ok2 then return nil end;return tostring(id or""):match("(%d+)")end
local function validDanceTrack(track)if not track then return false end;local okLoop,looped=pcall(function()return track.Looped end);if not okLoop or not looped then return false end;local okP,p=pcall(function()return track.Priority end);if okP and p~=Enum.AnimationPriority.Action and p~=Enum.AnimationPriority.Action2 and p~=Enum.AnimationPriority.Action3 and p~=Enum.AnimationPriority.Action4 then return false end;return animationId(track)~=nil end
local function stopSyncTrack()if syncTrack then pcall(function()syncTrack:Stop(.12)end);pcall(function()syncTrack:Destroy()end);syncTrack=nil end end
local function sliderPct()return(leadSpeed-.50)/(1.75-.50)end
local function updateSpeedVisual()if speedLabel then speedLabel.Text=string.format("%.2f×",leadSpeed)end;local p=math.clamp(sliderPct(),0,1);if sliderFill then sliderFill.Size=UDim2.new(p,0,1,0)end;if sliderThumb then sliderThumb.Position=UDim2.new(p,0,.5,0)end end
local function applyLeaderSpeed()leadSpeed=clampSpeed(leadSpeed);updateSpeedVisual();if latestLeadTrack and validDanceTrack(latestLeadTrack)then pcall(function()latestLeadTrack:AdjustSpeed(leadSpeed)end)end;if leadSyncActive and isLead()then social:FireServer("leadSyncSpeed",{speed=leadSpeed})end end
local function sendCurrent(kind)if not isLead()then return end;local track=latestLeadTrack;if not validDanceTrack(track)then if statusLabel then statusLabel.Text="PLAY A DANCE FIRST"end;return end;pcall(function()track:AdjustSpeed(leadSpeed)end);social:FireServer(kind,{animationId=animationId(track),timePosition=tonumber(track.TimePosition)or 0,speed=leadSpeed})end
local function bindAnimator()local a=animator();if not a or a==boundAnimator then return end;if animationConn then animationConn:Disconnect()end;if runningConn then runningConn:Disconnect()end;boundAnimator=a;animationConn=a.AnimationPlayed:Connect(function(track)task.delay(.06,function()if track and track.Parent~=nil and validDanceTrack(track)then latestLeadTrack=track;if isLead()then pcall(function()track:AdjustSpeed(leadSpeed)end)end;if leadSyncActive and isLead()then sendCurrent("leadSyncDance")end end end)end);local h=humanoid();if h then runningConn=h.Running:Connect(function(speed)if speed>.45 and leadSyncActive and isLead()then leadSyncActive=false;social:FireServer("leadSyncStop",{});if statusLabel then statusLabel.Text="SYNC OFF • MOVED"end end end)end end
local function playFollower(data)if isLead()or carryBusy()then return end;local h=humanoid();if not h or h.Health<=0 then return end;local a=animator();if not a then a=Instance.new("Animator");a.Parent=h end;stopSyncTrack();local anim=Instance.new("Animation");anim.AnimationId="rbxassetid://"..tostring(data.animationId or"");local ok,t=pcall(function()return a:LoadAnimation(anim)end);anim:Destroy();if not ok or not t then return end;syncTrack=t;local speed=clampSpeed(data.speed);pcall(function()t.Priority=Enum.AnimationPriority.Action;t.Looped=true;t:Play(.1);t:AdjustSpeed(speed)end);task.delay(.08,function()if syncTrack~=t then return end;local elapsed=0;pcall(function()elapsed=math.max(0,workspace:GetServerTimeNow()-(tonumber(data.serverTime)or workspace:GetServerTimeNow()))end);pcall(function()t.TimePosition=math.max(0,(tonumber(data.timePosition)or 0)+elapsed*speed)end)end)end
local function setFollowerSpeed(data)if syncTrack then pcall(function()syncTrack:AdjustSpeed(clampSpeed(data and data.speed))end)end end
local function removeBar()if bar then bar:Destroy()end;bar=nil;statusLabel=nil;speedLabel=nil;sliderFill=nil;sliderThumb=nil end
local function applyPanelMode()
 local g=pg:FindFirstChild("BBYASocialHangoutUI");local p=g and g:FindFirstChild("DancePanel",true);if not p or not p:IsA("Frame")then return false end;local catalog=p:FindFirstChild("BBYADanceCatalogV1");if not originalPanel or originalPanel.panel~=p then originalPanel={panel=p,pos=p.Position,size=p.Size,catalogPos=catalog and catalog.Position,catalogSize=catalog and catalog.Size}end;removeBar()
 if isLead()then
  p.Position=UDim2.new(1,-18,.5,18);p.AnchorPoint=Vector2.new(1,.5);p.Size=UDim2.fromOffset(330,550);p:SetAttribute("BBYALeadDancePanel",true);for _,d in ipairs(p:GetChildren())do if d:IsA("TextLabel")and string.find(string.upper(d.Text or""),"DANCE",1,true)then d.Text="LEAD DANCE";break end end;if catalog then catalog.Position=UDim2.fromOffset(14,158);catalog.Size=UDim2.new(1,-28,1,-172)end
  bar=Instance.new("Frame");bar.Name="LeadSyncBar";bar.Position=UDim2.fromOffset(14,48);bar.Size=UDim2.new(1,-28,0,102);bar.BackgroundTransparency=1;bar.Parent=p
  local function b(txt,pos,size,col)local q=Instance.new("TextButton");q.Text=txt;q.Position=pos;q.Size=size;q.BackgroundColor3=col;q.BackgroundTransparency=.12;q.BorderSizePixel=0;q.TextColor3=Color3.fromRGB(245,245,248);q.Font=Enum.Font.GothamBold;q.TextSize=9;q.Parent=bar;local c=Instance.new("UICorner");c.CornerRadius=UDim.new(0,8);c.Parent=q;return q end
  local sync=b("SYNC",UDim2.fromOffset(0,0),UDim2.new(.5,-4,0,34),Color3.fromRGB(47,82,72));local unsync=b("UNSYNC",UDim2.new(.5,4,0,0),UDim2.new(.5,-4,0,34),Color3.fromRGB(82,41,48))
  statusLabel=Instance.new("TextLabel");statusLabel.BackgroundTransparency=1;statusLabel.Position=UDim2.fromOffset(0,36);statusLabel.Size=UDim2.new(.56,0,0,18);statusLabel.Text="LEAD READY";statusLabel.TextColor3=Color3.fromRGB(170,172,184);statusLabel.Font=Enum.Font.GothamBold;statusLabel.TextSize=7;statusLabel.TextXAlignment=Enum.TextXAlignment.Left;statusLabel.Parent=bar
  speedLabel=Instance.new("TextLabel");speedLabel.BackgroundTransparency=1;speedLabel.Position=UDim2.new(.62,0,0,36);speedLabel.Size=UDim2.new(.38,0,0,18);speedLabel.TextColor3=Color3.fromRGB(245,245,248);speedLabel.Font=Enum.Font.GothamBlack;speedLabel.TextSize=9;speedLabel.TextXAlignment=Enum.TextXAlignment.Right;speedLabel.Parent=bar
  local rail=Instance.new("Frame");rail.Name="SpeedSlider";rail.Position=UDim2.fromOffset(0,67);rail.Size=UDim2.new(1,0,0,6);rail.BackgroundColor3=Color3.fromRGB(48,48,58);rail.BorderSizePixel=0;rail.Parent=bar;local rc=Instance.new("UICorner");rc.CornerRadius=UDim.new(1,0);rc.Parent=rail
  sliderFill=Instance.new("Frame");sliderFill.Size=UDim2.new(0,0,1,0);sliderFill.BackgroundColor3=Color3.fromRGB(247,55,158);sliderFill.BorderSizePixel=0;sliderFill.Parent=rail;local fc=Instance.new("UICorner");fc.CornerRadius=UDim.new(1,0);fc.Parent=sliderFill
  sliderThumb=Instance.new("Frame");sliderThumb.AnchorPoint=Vector2.new(.5,.5);sliderThumb.Position=UDim2.new(0,0,.5,0);sliderThumb.Size=UDim2.fromOffset(18,18);sliderThumb.BackgroundColor3=Color3.fromRGB(245,245,248);sliderThumb.BorderSizePixel=0;sliderThumb.Parent=rail;local tc=Instance.new("UICorner");tc.CornerRadius=UDim.new(1,0);tc.Parent=sliderThumb
  local hit=Instance.new("TextButton");hit.Text="";hit.BackgroundTransparency=1;hit.Position=UDim2.fromOffset(-8,-12);hit.Size=UDim2.new(1,16,0,30);hit.Parent=rail;local dragging=false
  local function setFromX(x)local pct=math.clamp((x-rail.AbsolutePosition.X)/math.max(1,rail.AbsoluteSize.X),0,1);leadSpeed=.50+pct*1.25;leadSpeed=math.floor(leadSpeed*100+.5)/100;applyLeaderSpeed()end
  hit.InputBegan:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 or i.UserInputType==Enum.UserInputType.Touch then dragging=true;setFromX(i.Position.X)end end);UserInputService.InputChanged:Connect(function(i)if dragging and(i.UserInputType==Enum.UserInputType.MouseMovement or i.UserInputType==Enum.UserInputType.Touch)then setFromX(i.Position.X)end end);UserInputService.InputEnded:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 or i.UserInputType==Enum.UserInputType.Touch then dragging=false end end)
  sync.Activated:Connect(function()if isLead()then leadSyncActive=true;sendCurrent("leadSyncStart")end end);unsync.Activated:Connect(function()if isLead()then leadSyncActive=false;social:FireServer("leadSyncStop",{});statusLabel.Text="SYNC OFF"end end);updateSpeedVisual()
 else leadSyncActive=false;if originalPanel and originalPanel.panel==p then p.AnchorPoint=Vector2.new(0,0);p.Position=originalPanel.pos;p.Size=originalPanel.size;p:SetAttribute("BBYALeadDancePanel",false);if catalog and originalPanel.catalogPos then catalog.Position=originalPanel.catalogPos;catalog.Size=originalPanel.catalogSize end end end;bindAnimator();return true
end
social.OnClientEvent:Connect(function(kind,data)data=type(data)=="table"and data or{};if kind=="leadSyncDance"then playFollower(data)elseif kind=="leadSyncSpeed"then setFollowerSpeed(data)elseif kind=="leadSyncStop"then stopSyncTrack()elseif kind=="leadSyncStatus"and isLead()then leadSyncActive=data.active==true;leadSpeed=clampSpeed(data.speed or leadSpeed);updateSpeedVisual();if statusLabel then statusLabel.Text=leadSyncActive and("SYNC • "..tostring(data.count or 0).." CROWD")or tostring(data.message or"SYNC OFF")end end end)
player:GetAttributeChangedSignal("BBYAHasLeadRole"):Connect(function()if not isLead()and leadSyncActive then social:FireServer("leadSyncStop",{});leadSyncActive=false end;task.defer(applyPanelMode)end);player:GetAttributeChangedSignal("BBYAManagedRole"):Connect(function()if not isLead()and leadSyncActive then social:FireServer("leadSyncStop",{});leadSyncActive=false end;task.defer(applyPanelMode)end);player.CharacterAdded:Connect(function()stopSyncTrack();latestLeadTrack=nil;boundAnimator=nil;task.delay(.8,function()bindAnimator();applyPanelMode()end)end);pg.ChildAdded:Connect(function(c)if c.Name=="BBYASocialHangoutUI"then task.defer(applyPanelMode);task.delay(.4,applyPanelMode)end end);task.spawn(function()for _=1,40 do bindAnimator();if applyPanelMode()then break end;task.wait(.25)end end)
print("[BBYA] LEAD Dance Sync v3 online: clean controls + draggable 0.50x–1.75x speed slider")