-- BBYA SOCIAL HUB — IN-SESSION AVATAR SWITCH CLIENT v3 COMPACT 2-COLUMN
-- Apply/outfit logic preserved. Layout only: same compact family as Music/Role, 2 columns, full-body Fit previews.

local Players=game:GetService("Players")
local ReplicatedStorage=game:GetService("ReplicatedStorage")
local AvatarEditorService=game:GetService("AvatarEditorService")
local player=Players.LocalPlayer
local pg=player:WaitForChild("PlayerGui")
local remote=ReplicatedStorage:WaitForChild("BBYAClubRemotes",30):WaitForChild("AvatarSwitch",30)
local old=pg:FindFirstChild("BBYAAvatarSwitchUI");if old then old:Destroy()end
local gui=Instance.new("ScreenGui");gui.Name="BBYAAvatarSwitchUI";gui.ResetOnSpawn=false;gui.IgnoreGuiInset=true;gui.DisplayOrder=935;gui.Parent=pg;gui:SetAttribute("BBYAUIAuthority","AVATAR_SWITCH_V3_COMPACT_2COL")
local C={bg=Color3.fromRGB(13,13,17),card=Color3.fromRGB(29,29,37),card2=Color3.fromRGB(38,38,48),white=Color3.fromRGB(245,245,248),muted=Color3.fromRGB(164,166,177),cyan=Color3.fromRGB(73,207,235),green=Color3.fromRGB(103,230,174),red=Color3.fromRGB(235,91,104)}
local function corner(o,r)local c=Instance.new("UICorner");c.CornerRadius=UDim.new(0,r or 10);c.Parent=o end
local function stroke(o,col,tr)local s=Instance.new("UIStroke");s.Color=col or C.muted;s.Thickness=1;s.Transparency=tr or .45;s.Parent=o end
local function label(p,v,pos,size,font,ts,col,align)local t=Instance.new("TextLabel");t.BackgroundTransparency=1;t.Text=tostring(v or"");t.Position=pos;t.Size=size;t.Font=font or Enum.Font.Gotham;t.TextSize=ts or 11;t.TextColor3=col or C.white;t.TextXAlignment=align or Enum.TextXAlignment.Left;t.TextYAlignment=Enum.TextYAlignment.Center;t.TextTruncate=Enum.TextTruncate.AtEnd;t.Parent=p;return t end
local function btn(p,v,pos,size,col)local b=Instance.new("TextButton");b.Text=v;b.Position=pos;b.Size=size;b.BackgroundColor3=col or C.card;b.BackgroundTransparency=.12;b.BorderSizePixel=0;b.TextColor3=C.white;b.Font=Enum.Font.GothamBold;b.TextSize=9;b.Parent=p;corner(b,9);stroke(b,C.muted,.55);return b end
local panel=Instance.new("Frame");panel.AnchorPoint=Vector2.new(1,.5);panel.Position=UDim2.new(1,-18,.5,18);panel.Size=UDim2.fromOffset(420,420);panel.BackgroundColor3=C.bg;panel.BackgroundTransparency=.18;panel.BorderSizePixel=0;panel.Visible=false;panel.ClipsDescendants=true;panel.Parent=gui;corner(panel,16);stroke(panel,C.cyan,.35)
label(panel,"GANTI AVATAR",UDim2.fromOffset(16,10),UDim2.new(1,-64,0,22),Enum.Font.GothamBlack,16,C.white);label(panel,"Pilih outfit Roblox milikmu • tidak perlu rejoin",UDim2.fromOffset(16,32),UDim2.new(1,-64,0,16),Enum.Font.Gotham,8,C.muted);local close=btn(panel,"×",UDim2.new(1,-44,0,9),UDim2.fromOffset(30,28),C.card);close.TextSize=17
local status=label(panel,"Tap REFRESH untuk membaca koleksi outfit Roblox kamu.",UDim2.fromOffset(16,53),UDim2.new(1,-132,0,30),Enum.Font.GothamMedium,8,C.cyan);local refresh=btn(panel,"REFRESH",UDim2.new(1,-112,0,53),UDim2.fromOffset(96,30),C.card2)
local holder=Instance.new("ScrollingFrame");holder.Position=UDim2.fromOffset(14,90);holder.Size=UDim2.new(1,-28,1,-104);holder.BackgroundTransparency=1;holder.BorderSizePixel=0;holder.ScrollBarThickness=3;holder.AutomaticCanvasSize=Enum.AutomaticSize.Y;holder.CanvasSize=UDim2.new();holder.Parent=panel
local grid=Instance.new("UIGridLayout");grid.CellPadding=UDim2.fromOffset(8,8);grid.CellSize=UDim2.new(.5,-4,0,176);grid.FillDirectionMaxCells=2;grid.Parent=holder
local loading=false;local pages=nil;local outfitsPermission=false
local function clearCards()for _,c in ipairs(holder:GetChildren())do if c~=grid then c:Destroy()end end end
local function setStatus(v,col)status.Text=tostring(v);status.TextColor3=col or C.cyan end
local function itemId(item)return tonumber(item.Id or item.id or item.OutfitId or item.outfitId)end
local function addOutfit(item)
 local id=itemId(item);if not id then return end;local name=tostring(item.Name or item.name or("OUTFIT "..id));local card=Instance.new("Frame");card.BackgroundColor3=C.card;card.BackgroundTransparency=.12;card.BorderSizePixel=0;card.Parent=holder;corner(card,10);stroke(card,C.muted,.62)
 local img=Instance.new("ImageLabel");img.Position=UDim2.fromOffset(6,6);img.Size=UDim2.new(1,-12,1,-48);img.BackgroundColor3=C.card2;img.BackgroundTransparency=.08;img.BorderSizePixel=0;img.ScaleType=Enum.ScaleType.Fit;img.Image=string.format("rbxthumb://type=Outfit&id=%d&w=420&h=420",id);img.Parent=card;corner(img,8)
 label(card,name,UDim2.new(0,7,1,-40),UDim2.new(1,-14,0,15),Enum.Font.GothamBold,8,C.white,Enum.TextXAlignment.Center);local apply=btn(card,"APPLY",UDim2.new(0,7,1,-23),UDim2.new(1,-14,0,19),Color3.fromRGB(41,78,70));apply.TextSize=8;apply.Activated:Connect(function()setStatus("Applying "..name.."…",C.cyan);remote:FireServer("applyOutfit",id)end)
end
local function renderPage()if not pages then return end;clearCards();local ok,data=pcall(function()return pages:GetCurrentPage()end);if not ok or type(data)~="table"then setStatus("Koleksi outfit belum tersedia.",C.red);return end;for _,item in ipairs(data)do addOutfit(item)end;setStatus(#data>0 and(tostring(#data).." outfit ditemukan • tap APPLY")or"Belum ada outfit di halaman ini.",#data>0 and C.green or C.muted)end
local function loadOutfits()if loading then return end;loading=true;local ok,result=pcall(function()return AvatarEditorService:GetOutfitsAsync(Enum.OutfitSource.All,Enum.OutfitType.Avatar)end);if ok and result then pages=result;outfitsPermission=true;renderPage();loading=false;return end;loading=false;if not outfitsPermission then setStatus("Izinkan BBYA membaca daftar outfit Roblox kamu.",C.cyan);pcall(function()AvatarEditorService:PromptAllowInventoryReadAccess()end)else setStatus("Outfit Roblox belum dapat dimuat. Coba REFRESH.",C.red)end end
refresh.Activated:Connect(loadOutfits);AvatarEditorService.PromptAllowInventoryReadAccessCompleted:Connect(function(result)if result==Enum.AvatarPromptResult.Success then outfitsPermission=true;setStatus("Permission granted • loading outfits…",C.green);task.defer(loadOutfits)else setStatus("Akses outfit tidak diberikan.",C.muted)end end);remote.OnClientEvent:Connect(function(kind,data)if kind=="status"and type(data)=="table"then setStatus(tostring(data.message or""),data.ok and C.green or C.red)end end)
local function menuButton()local m=pg:FindFirstChild("BBYACommandMenuUI");return m and m:FindFirstChild("MenuButton",true)end
local function roleButton(v)local g=pg:FindFirstChild("BBYARolePanelUI");local b=g and g:FindFirstChild("RolePanelOpen",true);if b then b.Visible=v end end
local function closePanel()panel.Visible=false;local mb=menuButton();if mb then mb.Visible=true end;roleButton(true)end;close.Activated:Connect(closePanel);player.CharacterAdded:Connect(closePanel)
local function layout()local cam=workspace.CurrentCamera;local vp=cam and cam.ViewportSize or Vector2.new(1280,720);local s=math.clamp(math.min(vp.Y-84,420),330,420);panel.Size=UDim2.fromOffset(s,s);panel.Position=UDim2.new(1,-18,.5,18);grid.FillDirectionMaxCells=2;grid.CellSize=UDim2.new(.5,-4,0,math.max(160,math.floor(s*.43)))end
local function inject()local menu=pg:FindFirstChild("BBYACommandMenuUI");local drawer=menu and menu:FindFirstChild("FeatureDrawer",true);local list=drawer and drawer:FindFirstChild("FeatureList",true);if not list then return false end;local oldB=list:FindFirstChild("BBYAAvatarSwitchMenuButton");if oldB then return true end;local template=nil;for _,d in ipairs(list:GetChildren())do if d:IsA("TextButton")then template=d;break end end;local b=template and template:Clone()or Instance.new("TextButton");b.Name="BBYAAvatarSwitchMenuButton";b.Text="AVATAR";b.Visible=true;b.Active=true;b.AutoButtonColor=true;if not template then b.Size=UDim2.new(1,-8,0,38);b.BackgroundColor3=C.card;b.BorderSizePixel=0;b.TextColor3=C.white;b.Font=Enum.Font.GothamBold;b.TextSize=11;corner(b,8)end;b:SetAttribute("BBYAInjectedAuthority","AVATAR_SWITCH_V3_COMPACT_2COL");b.Parent=list;b.Activated:Connect(function()if drawer then drawer.Visible=false end;local mb=menuButton();if mb then mb.Visible=false end;roleButton(false);layout();panel.Visible=true;task.defer(loadOutfits)end);return true end
pg.ChildAdded:Connect(function(c)if c.Name=="BBYACommandMenuUI"then task.defer(inject);task.delay(.2,inject)end end);task.spawn(function()for _=1,40 do if inject()then break end;task.wait(.25)end end);local cam=workspace.CurrentCamera;if cam then cam:GetPropertyChangedSignal("ViewportSize"):Connect(layout)end;task.defer(layout)
print("[BBYA] Avatar Switch v3 online: compact right dock / 2 columns / full-body Fit previews")