local W=game:GetService("Workspace")
local ReplicatedStorage=game:GetService("ReplicatedStorage")
local root=W:FindFirstChild("BBYA_ZERO_BUILD") or Instance.new("Folder",W);root.Name="BBYA_ZERO_BUILD"
local old=root:FindFirstChild("SupportDashboard");if old then old:Destroy() end
local model=Instance.new("Model",root);model.Name="SupportDashboard"
local board=Instance.new("Part");board.Name="SawerDashboard";board.Anchored=true;board.CanCollide=false;board.Size=Vector3.new(22,11,.6);board.CFrame=CFrame.new(43,7,-32);board.Color=Color3.fromRGB(12,11,15);board.Material=Enum.Material.Metal;board.Parent=model
local glow=Instance.new("Part");glow.Name="DashboardGlow";glow.Anchored=true;glow.CanCollide=false;glow.Size=Vector3.new(22.6,11.6,.18);glow.CFrame=board.CFrame*CFrame.new(0,0,-.39);glow.Color=Color3.fromRGB(255,42,157);glow.Material=Enum.Material.Neon;glow.Parent=model
local face=Instance.new("Part");face.Name="DashboardFace";face.Anchored=true;face.CanCollide=false;face.Size=Vector3.new(21.8,10.8,.12);face.CFrame=board.CFrame*CFrame.new(0,0,-.51);face.Color=Color3.fromRGB(18,16,22);face.Material=Enum.Material.SmoothPlastic;face.Parent=model
local gui=Instance.new("SurfaceGui");gui.Name="SawerUI";gui.Face=Enum.NormalId.Front;gui.AlwaysOnTop=false;gui.LightInfluence=.15;gui.PixelsPerStud=55;gui.Parent=face
local bg=Instance.new("Frame");bg.Size=UDim2.fromScale(1,1);bg.BackgroundColor3=Color3.fromRGB(14,12,18);bg.BorderSizePixel=0;bg.Parent=gui
local grad=Instance.new("UIGradient");grad.Color=ColorSequence.new({ColorSequenceKeypoint.new(0,Color3.fromRGB(35,15,30)),ColorSequenceKeypoint.new(1,Color3.fromRGB(12,12,16))});grad.Rotation=90;grad.Parent=bg
local title=Instance.new("TextLabel");title.BackgroundTransparency=1;title.Position=UDim2.fromScale(.06,.07);title.Size=UDim2.fromScale(.88,.16);title.Text="SUPPORT BBYA";title.TextColor3=Color3.fromRGB(255,70,170);title.Font=Enum.Font.GothamBold;title.TextScaled=true;title.TextXAlignment=Enum.TextXAlignment.Left;title.Parent=bg
local sub=Instance.new("TextLabel");sub.BackgroundTransparency=1;sub.Position=UDim2.fromScale(.06,.22);sub.Size=UDim2.fromScale(.88,.08);sub.Text="SAWER • SUPPORTER WALL";sub.TextColor3=Color3.fromRGB(180,177,188);sub.Font=Enum.Font.GothamMedium;sub.TextScaled=true;sub.TextXAlignment=Enum.TextXAlignment.Left;sub.Parent=bg
local line=Instance.new("Frame");line.Position=UDim2.fromScale(.06,.33);line.Size=UDim2.fromScale(.88,.008);line.BackgroundColor3=Color3.fromRGB(255,42,157);line.BorderSizePixel=0;line.Parent=bg
local top=Instance.new("TextLabel");top.BackgroundTransparency=1;top.Position=UDim2.fromScale(.06,.39);top.Size=UDim2.fromScale(.42,.1);top.Text="TOP SUPPORTERS";top.TextColor3=Color3.fromRGB(245,245,248);top.Font=Enum.Font.GothamBold;top.TextScaled=true;top.TextXAlignment=Enum.TextXAlignment.Left;top.Parent=bg
local rows={"01  —  Waiting for supporter","02  —  Waiting for supporter","03  —  Waiting for supporter"}
for i,t in ipairs(rows) do local r=Instance.new("TextLabel");r.BackgroundColor3=Color3.fromRGB(25,22,31);r.BackgroundTransparency=.12;r.BorderSizePixel=0;r.Position=UDim2.fromScale(.06,.49+(i-1)*.115);r.Size=UDim2.fromScale(.58,.09);r.Text="   "..t;r.TextColor3=Color3.fromRGB(220,218,225);r.Font=Enum.Font.GothamMedium;r.TextScaled=true;r.TextXAlignment=Enum.TextXAlignment.Left;r.Parent=bg;local c=Instance.new("UICorner");c.CornerRadius=UDim.new(0,8);c.Parent=r end
local cta=Instance.new("TextLabel");cta.BackgroundColor3=Color3.fromRGB(69,20,52);cta.BorderSizePixel=0;cta.Position=UDim2.fromScale(.69,.49);cta.Size=UDim2.fromScale(.25,.32);cta.Text="OPEN\nSUPPORT\nMENU";cta.TextColor3=Color3.fromRGB(255,255,255);cta.Font=Enum.Font.GothamBold;cta.TextScaled=true;cta.Parent=bg;local cc=Instance.new("UICorner");cc.CornerRadius=UDim.new(0,12);cc.Parent=cta
local prompt=Instance.new("ProximityPrompt");prompt.Name="OpenSawerMenu";prompt.ActionText="Open Support";prompt.ObjectText="BBYA Support Dashboard";prompt.KeyboardKeyCode=Enum.KeyCode.E;prompt.HoldDuration=0;prompt.MaxActivationDistance=12;prompt.RequiresLineOfSight=false;prompt.Parent=face
local remotes=ReplicatedStorage:FindFirstChild("BBYAClubRemotes")
local state=remotes and remotes:FindFirstChild("State")
prompt.Triggered:Connect(function(player)if state then state:FireClient(player,"openSupport",true) end end)
print("[BBYA] Physical sawer dashboard mounted on entrance-right wall")