-- BBYA Social Hub v1.7 functional interaction backend
local Players=game:GetService("Players")
local ReplicatedStorage=game:GetService("ReplicatedStorage")
local Debris=game:GetService("Debris")
local Lighting=game:GetService("Lighting")
local QUEEN_ID=4271188557
local remotes=ReplicatedStorage:FindFirstChild("BBYA_Remotes")or Instance.new("Folder");remotes.Name="BBYA_Remotes";remotes.Parent=ReplicatedStorage
local function remote(n)local r=remotes:FindFirstChild(n)or Instance.new("RemoteEvent");r.Name=n;r.Parent=remotes;return r end
local DanceRemote=remote("Dance"),SyncRemote=remote("SyncDance"),TitleRemote=remote("SetTitle"),FXRemote=remote("FX"),TeleportRemote=remote("Teleport"),AdminRemote=remote("QueenAdmin"),NoticeRemote=remote("Notice"),FeedbackRemote=remote("Feedback")
local lastEmote,cooldown={},{}
local function ready(p,k,s)local id=p.UserId..":"..k;local n=os.clock();if cooldown[id]and n-cooldown[id]<s then return false end;cooldown[id]=n;return true end
local allowed={dance=true,dance2=true,dance3=true,wave=true,cheer=true,laugh=true,point=true}
local spots={DANCE=CFrame.new(0,5,0),VIP=CFrame.new(-30,8,8),BAR=CFrame.new(-31,6,24),PHOTO=CFrame.new(31,6,25),CHILL=CFrame.new(31,6,-30),DJ=CFrame.new(0,7,-39),POOL=CFrame.new(0,24,35),SALON=CFrame.new(69,5,18),SUPPORT=CFrame.new(-68,5,28)}
local function feedback(p,t)FeedbackRemote:FireClient(p,t)end
local function isQueen(p)return p and p.UserId==QUEEN_ID end
local function play(p,n)local h=p.Character and p.Character:FindFirstChildOfClass("Humanoid");if not h then return false end;if n=="stop"then for _,tr in ipairs(h:GetPlayingAnimationTracks())do tr:Stop(.15)end;lastEmote[p.UserId]=nil;return true end;if not allowed[n]then return false end;lastEmote[p.UserId]=n;local ok=pcall(function()h:PlayEmote(n)end);return ok end
DanceRemote.OnServerEvent:Connect(function(p,n)if typeof(n)~="string"or not ready(p,"dance",.15)then return end;n=string.lower(n);if play(p,n)then feedback(p,n=="stop"and"Dance stopped"or("Playing "..string.upper(n)))else feedback(p,"Emote unavailable on this avatar")end end)
SyncRemote.OnServerEvent:Connect(function(p,uid)if typeof(uid)~="number"or not ready(p,"sync",.6)then return end;local t=Players:GetPlayerByUserId(uid);local a=p.Character and p.Character:FindFirstChild("HumanoidRootPart");local b=t and t.Character and t.Character:FindFirstChild("HumanoidRootPart");if not a or not b or(a.Position-b.Position).Magnitude>35 then feedback(p,"No dancer nearby");return end;local n=lastEmote[t.UserId];if n and play(p,n)then feedback(p,"Synced with "..t.DisplayName)else feedback(p,"That player is not dancing")end end)
TeleportRemote.OnServerEvent:Connect(function(p,s)if typeof(s)~="string"or not ready(p,"tp",.35)then return end;local cf=spots[string.upper(s)];if cf and p.Character then p.Character:PivotTo(cf);feedback(p,"Moved to "..string.upper(s))else feedback(p,"Area unavailable")end end)
FXRemote.OnServerEvent:Connect(function(p,k)if(k~="glowstick"and k~="confetti")or not ready(p,"fx",k=="confetti"and 3 or .6)then return end;local c=p.Character;local r=c and c:FindFirstChild("HumanoidRootPart");if not r then return end;if k=="glowstick"then local existing=p.Backpack:FindFirstChild("BBYA Glowstick")or c:FindFirstChild("BBYA Glowstick");if existing then existing:Destroy();feedback(p,"Glowstick removed");return end;local tool=Instance.new("Tool");tool.Name="BBYA Glowstick";tool.RequiresHandle=true;local h=Instance.new("Part");h.Name="Handle";h.Size=Vector3.new(.35,3,.35);h.Material=Enum.Material.Neon;h.Color=Color3.fromRGB(255,70,200);h.CanCollide=false;h.Parent=tool;local l=Instance.new("PointLight");l.Range=10;l.Brightness=1;l.Color=h.Color;l.Parent=h;tool.Parent=p.Backpack;feedback(p,"Glowstick equipped")else for i=1,20 do local q=Instance.new("Part");q.Size=Vector3.new(.25,.25,.25);q.Material=Enum.Material.Neon;q.Color=Color3.fromHSV(math.random(),.8,1);q.CanCollide=false;q.CFrame=r.CFrame*CFrame.new(math.random(-4,4),math.random(2,7),math.random(-4,4));q.Parent=workspace;q.AssemblyLinearVelocity=Vector3.new(math.random(-10,10),math.random(10,22),math.random(-10,10));Debris:AddItem(q,2.5)end;feedback(p,"Confetti!")end end)
TitleRemote.OnServerEvent:Connect(function(p,uid,title)if not isQueen(p)or typeof(uid)~="number"or typeof(title)~="string"then return end;title=string.sub(title:gsub("[%c]",""),1,24);local t=Players:GetPlayerByUserId(uid);if not t then return end;t:SetAttribute("BBYACustomTitle",title);local head=t.Character and t.Character:FindFirstChild("Head");if not head then return end;local old=head:FindFirstChild("BBYACustomTitleTag");if old then old:Destroy()end;if title==""then return end;local g=Instance.new("BillboardGui");g.Name="BBYACustomTitleTag";g.Size=UDim2.fromOffset(180,34);g.StudsOffset=Vector3.new(0,3.5,0);g.MaxDistance=45;g.Parent=head;local lab=Instance.new("TextLabel");lab.BackgroundTransparency=1;lab.Size=UDim2.fromScale(1,1);lab.Font=Enum.Font.GothamBold;lab.Text=title;lab.TextColor3=Color3.fromRGB(255,180,235);lab.TextScaled=true;lab.Parent=g end)
local function announce(t)t=string.sub(tostring(t or""):gsub("[%c]"," "),1,120);if t~=""then NoticeRemote:FireAllClients(t)end end
AdminRemote.OnServerEvent:Connect(function(p,a,x)if not isQueen(p)or not ready(p,"admin",.25)then return end;a=string.lower(tostring(a or""));if a=="announce"then announce(x)elseif a=="party"then workspace:SetAttribute("BBYAPartyMode",true);Lighting.ClockTime=22;announce("BBYA PARTY MODE ON")elseif a=="normal"then workspace:SetAttribute("BBYAPartyMode",false);Lighting.ClockTime=21.5;announce("BBYA normal mode")else local uid=tonumber(x);local t=uid and Players:GetPlayerByUserId(uid);if a=="kick"and t and t~=p then t:Kick("Removed by BBYA Queen")elseif a=="bring"and t and t.Character and p.Character then t.Character:PivotTo(p.Character:GetPivot()*CFrame.new(3,0,0))elseif a=="goto"and t and t.Character and p.Character then p.Character:PivotTo(t.Character:GetPivot()*CFrame.new(3,0,0))elseif a=="speed"then local h=p.Character and p.Character:FindFirstChildOfClass("Humanoid");if h then h.WalkSpeed=math.clamp(tonumber(x)or 32,16,80)end elseif a=="speednormal"then local h=p.Character and p.Character:FindFirstChildOfClass("Humanoid");if h then h.WalkSpeed=16 end end end end)
local function tag(p)p:SetAttribute("BBYAQueen",isQueen(p));if isQueen(p)then p:SetAttribute("BBYARole","BBYA_QUEEN");p:SetAttribute("BBYAAllAccess",true);p:SetAttribute("IsVIP",true)elseif not p:GetAttribute("BBYARole")then p:SetAttribute("BBYARole","GUEST")end end
Players.PlayerAdded:Connect(tag);for _,p in ipairs(Players:GetPlayers())do tag(p)end
print("[BBYA] v1.7 functional backend loaded")