-- BBYA Social Hub v1.8 client - unified music-style HUD
local Players=game:GetService("Players");local RS=game:GetService("ReplicatedStorage");local Lighting=game:GetService("Lighting");local TweenService=game:GetService("TweenService")
local player=Players.LocalPlayer;local remotes=RS:WaitForChild("BBYA_Remotes");local Dance=remotes:WaitForChild("Dance");local Sync=remotes:WaitForChild("SyncDance");local FX=remotes:WaitForChild("FX");local TP=remotes:WaitForChild("Teleport");local Feedback=remotes:WaitForChild("Feedback")
local gui=Instance.new("ScreenGui");gui.Name="BBYA_UI";gui.ResetOnSpawn=false;gui.DisplayOrder=20;gui.Parent=player:WaitForChild("PlayerGui")
local PINK=Color3.fromRGB(255,105,215);local BG=Color3.fromRGB(16,13,24);local BTN=Color3.fromRGB(50,32,68)
local function corner(o,r)local c=Instance.new("UICorner");c.CornerRadius=UDim.new(0,r or 10);c.Parent=o end
local toast=Instance.new("TextLabel");toast.AnchorPoint=Vector2.new(.5,0);toast.Position=UDim2.new(.5,0,0,52);toast.Size=UDim2.fromOffset(300,38);toast.BackgroundColor3=BG;toast.BackgroundTransparency=.08;toast.TextColor3=Color3.new(1,1,1);toast.Font=Enum.Font.GothamBold;toast.TextSize=15;toast.Visible=false;toast.Parent=gui;corner(toast,9)
local token=0;local function notify(t)token+=1;local mine=token;toast.Text=t;toast.Visible=true;task.delay(2,function()if mine==token then toast.Visible=false end end)end;Feedback.OnClientEvent:Connect(notify)
local open=Instance.new("TextButton");open.Size=UDim2.fromOffset(78,38);open.Text="BBYA";open.Font=Enum.Font.GothamBold;open.TextSize=18;open.BackgroundColor3=Color3.fromRGB(35,18,48);open.TextColor3=Color3.new(1,1,1);open.Parent=gui;corner(open,8)
local frame=Instance.new("Frame");frame.Size=UDim2.fromOffset(300,344);frame.BackgroundColor3=BG;frame.BackgroundTransparency=.04;frame.Visible=false;frame.ClipsDescendants=true;frame.Parent=gui;corner(frame,10)
local title=Instance.new("TextLabel");title.Size=UDim2.new(1,-45,0,38);title.Position=UDim2.fromOffset(12,3);title.BackgroundTransparency=1;title.Text="♥ BBYA SOCIAL • HUB";title.TextColor3=PINK;title.Font=Enum.Font.GothamBlack;title.TextSize=17;title.TextXAlignment=Enum.TextXAlignment.Left;title.Parent=frame
local close=Instance.new("TextButton");close.Size=UDim2.fromOffset(32,32);close.Position=UDim2.new(1,-38,0,5);close.Text="×";close.TextSize=24;close.TextColor3=Color3.new(1,1,1);close.BackgroundColor3=BTN;close.Parent=frame;corner(close,7)
local scroll=Instance.new("ScrollingFrame");scroll.Size=UDim2.new(1,-12,1,-48);scroll.Position=UDim2.fromOffset(6,42);scroll.BackgroundTransparency=1;scroll.BorderSizePixel=0;scroll.ScrollBarThickness=4;scroll.AutomaticCanvasSize=Enum.AutomaticSize.Y;scroll.CanvasSize=UDim2.new();scroll.Parent=frame
local grid=Instance.new("UIGridLayout");grid.CellSize=UDim2.fromOffset(88,44);grid.CellPadding=UDim2.fromOffset(6,6);grid.HorizontalAlignment=Enum.HorizontalAlignment.Center;grid.Parent=scroll
local order=0;local function button(txt,cb)order+=1;local b=Instance.new("TextButton");b.LayoutOrder=order;b.Text=txt;b.Font=Enum.Font.GothamBold;b.TextColor3=Color3.new(1,1,1);b.BackgroundColor3=BTN;b.TextWrapped=true;b.TextScaled=true;local c=Instance.new("UITextSizeConstraint");c.MinTextSize=9;c.MaxTextSize=15;c.Parent=b;corner(b,7);b.Parent=scroll;b.Activated:Connect(function()cb();b.BackgroundColor3=Color3.fromRGB(90,45,105);task.delay(.15,function()if b.Parent then b.BackgroundColor3=BTN end end)end);return b end
open.Activated:Connect(function()frame.Visible=not frame.Visible end);close.Activated:Connect(function()frame.Visible=false end)
for _,e in ipairs({"dance","dance2","dance3","wave","cheer","laugh"})do button(string.upper(e),function()Dance:FireServer(e)end)end;button("STOP",function()Dance:FireServer("stop")end)
button("SYNC NEAR",function()local r=player.Character and player.Character:FindFirstChild("HumanoidRootPart");if not r then return end;local best,bd=nil,35;for _,p in ipairs(Players:GetPlayers())do local pr=p~=player and p.Character and p.Character:FindFirstChild("HumanoidRootPart");if pr then local d=(pr.Position-r.Position).Magnitude;if d<bd then bd=d;best=p end end end;if best then Sync:FireServer(best.UserId)else notify("No player nearby")end end)
button("GLOWSTICK",function()FX:FireServer("glowstick")end);button("CONFETTI",function()FX:FireServer("confetti")end)
for _,s in ipairs({"DANCE","VIP","BAR","PHOTO","CHILL","DJ","POOL","SALON","SUPPORT"})do button(s,function()TP:FireServer(s)end)end
local music=Instance.new("Frame");music.Size=UDim2.fromOffset(270,120);music.BackgroundColor3=BG;music.BackgroundTransparency=.03;music.Visible=false;music.Parent=gui;corner(music,10)
local mt=Instance.new("TextLabel");mt.Size=UDim2.new(1,-16,0,27);mt.Position=UDim2.fromOffset(8,6);mt.BackgroundTransparency=1;mt.Text="♫ BBYA MUSIC • 24/7";mt.Font=Enum.Font.GothamBlack;mt.TextSize=15;mt.TextColor3=PINK;mt.TextXAlignment=Enum.TextXAlignment.Left;mt.Parent=music
local now=Instance.new("TextLabel");now.Size=UDim2.new(1,-16,0,38);now.Position=UDim2.fromOffset(8,31);now.BackgroundTransparency=1;now.Text="NOW PLAYING\nBBYA 24/7";now.Font=Enum.Font.GothamBold;now.TextSize=12;now.TextColor3=Color3.new(1,1,1);now.TextXAlignment=Enum.TextXAlignment.Left;now.Parent=music
local function sb(t,x,w)local b=Instance.new("TextButton");b.Size=UDim2.fromOffset(w,30);b.Position=UDim2.fromOffset(x,80);b.Text=t;b.Font=Enum.Font.GothamBold;b.TextSize=12;b.TextColor3=Color3.new(1,1,1);b.BackgroundColor3=BTN;b.Parent=music;corner(b,7);return b end
local mute=sb("MUTE",8,70);local vd=sb("VOL-",84,50);local vu=sb("VOL+",140,50);local hide=sb("HIDE",196,64);local volume=.65;local muted=false
local function sounds()local a={};for _,o in ipairs(workspace:GetDescendants())do if o:IsA("Sound")and(string.find(string.lower(o.Name),"music")or string.find(string.lower(o.Name),"bbya"))then table.insert(a,o)end end;return a end
local function refresh()local ss=sounds();now.Text="NOW PLAYING\n"..tostring(workspace:GetAttribute("BBYANowPlaying")or(#ss>0 and ss[1].Name or"BBYA 24/7"));for _,s in ipairs(ss)do s.Volume=muted and 0 or volume end end
mute.Activated:Connect(function()muted=not muted;mute.Text=muted and"UNMUTE"or"MUTE";refresh()end);vd.Activated:Connect(function()volume=math.max(0,volume-.1);muted=false;mute.Text="MUTE";refresh();notify("Volume "..math.floor(volume*100).."%")end);vu.Activated:Connect(function()volume=math.min(1,volume+.1);muted=false;mute.Text="MUTE";refresh();notify("Volume "..math.floor(volume*100).."%")end);hide.Activated:Connect(function()music.Visible=false end);button("MUSIC",function()music.Visible=not music.Visible;refresh()end)
local cam=workspace.CurrentCamera;local cine=false;local ci=1;local presets={CFrame.new(0,18,55)*CFrame.Angles(math.rad(-10),math.rad(180),0),CFrame.new(38,16,18)*CFrame.Angles(math.rad(-8),math.rad(130),0),CFrame.new(-38,18,-20)*CFrame.Angles(math.rad(-6),math.rad(-50),0),CFrame.new(0,28,-40)*CFrame.Angles(math.rad(-18),0,0)}
button("CINE CAM",function()cine=not cine;if cine then cam.CameraType=Enum.CameraType.Scriptable;TweenService:Create(cam,TweenInfo.new(.8),{CFrame=presets[ci]}):Play();notify("Cinematic camera ON")else cam.CameraType=Enum.CameraType.Custom;local h=player.Character and player.Character:FindFirstChildOfClass("Humanoid");if h then cam.CameraSubject=h end;notify("Cinematic camera OFF")end end);button("CAM NEXT",function()if not cine then notify("Turn CINE CAM on first");return end;ci=ci%#presets+1;TweenService:Create(cam,TweenInfo.new(.7),{CFrame=presets[ci]}):Play()end)
local gfx=2;local gb;gb=button("GRAPHICS MED",function()gfx=gfx%3+1;if gfx==1 then Lighting.GlobalShadows=false;Lighting.Brightness=2.2;gb.Text="GRAPHICS LOW"elseif gfx==2 then Lighting.GlobalShadows=true;Lighting.Brightness=2.6;gb.Text="GRAPHICS MED"else Lighting.GlobalShadows=true;Lighting.Brightness=3;Lighting.ExposureCompensation=.45;gb.Text="GRAPHICS HIGH"end;notify(gb.Text)end)
local function layout()local v=cam.ViewportSize;open.Position=UDim2.new(0,16,1,-58);frame.AnchorPoint=Vector2.new(0,.5);frame.Position=UDim2.new(0,12,.5,0);frame.Size=UDim2.fromOffset(math.min(300,v.X*.36),math.min(344,v.Y-100));music.AnchorPoint=Vector2.new(.5,0);music.Position=UDim2.new(.5,0,0,10)end;layout();cam:GetPropertyChangedSignal("ViewportSize"):Connect(layout)
task.spawn(function()while gui.Parent do if music.Visible then refresh()end;task.wait(2)end end)
print("[BBYA] v1.8 unified HUD loaded")