-- BBYA Social Hub runtime v1.1 FULL SOCIAL CLUB PACK
local Players=game:GetService("Players")
local Lighting=game:GetService("Lighting")
local TweenService=game:GetService("TweenService")
local Debris=game:GetService("Debris")
local BBYA_QUEEN_USER_ID=4271188557
local COLORS={Color3.fromRGB(255,55,170),Color3.fromRGB(155,70,255),Color3.fromRGB(45,190,255),Color3.fromRGB(255,90,220)}
local function part(par,n,s,cf,c,m,tr,col)local p=Instance.new("Part");p.Name=n;p.Size=s;p.CFrame=cf;p.Anchored=true;p.CanCollide=col~=false;p.Color=c;p.Material=m or Enum.Material.SmoothPlastic;p.Transparency=tr or 0;p.Parent=par;return p end
local function text(p,s,color)local g=Instance.new("SurfaceGui");g.Face=Enum.NormalId.Front;g.SizingMode=Enum.SurfaceGuiSizingMode.PixelsPerStud;g.PixelsPerStud=30;g.LightInfluence=.05;g.Parent=p;local t=Instance.new("TextLabel");t.BackgroundTransparency=1;t.Size=UDim2.fromScale(1,1);t.Font=Enum.Font.GothamBlack;t.Text=s;t.TextColor3=color or Color3.fromRGB(255,90,210);t.TextStrokeTransparency=.3;t.TextScaled=true;t.Parent=g end
local function sofa(f,n,cf,c)local seat=Instance.new("Seat");seat.Name=n.." Seat";seat.Size=Vector3.new(14,2,5);seat.CFrame=cf;seat.Anchored=true;seat.Color=c;seat.Material=Enum.Material.Fabric;seat.Parent=f;part(f,n.." Back",Vector3.new(14,4.5,1.2),cf*CFrame.new(0,2,2),c,Enum.Material.Fabric);part(f,n.." L",Vector3.new(1.2,3.2,5),cf*CFrame.new(-6.5,.8,0),c,Enum.Material.Fabric);part(f,n.." R",Vector3.new(1.2,3.2,5),cf*CFrame.new(6.5,.8,0),c,Enum.Material.Fabric)end
local function sign(f,n,cf,label,w)local b=part(f,n,Vector3.new(w or 14,2.4,.35),cf,Color3.fromRGB(20,8,30),Enum.Material.SmoothPlastic,0,false);text(b,label);return b end
local function prompt(p,action,obj,hold)local pr=Instance.new("ProximityPrompt");pr.ActionText=action;pr.ObjectText=obj;pr.HoldDuration=hold or 0;pr.MaxActivationDistance=10;pr.RequiresLineOfSight=false;pr.Parent=p;return pr end
local function findPlayer(q)if not q or q==""then return nil end;q=string.lower(q);for _,p in ipairs(Players:GetPlayers())do if string.sub(string.lower(p.Name),1,#q)==q or string.sub(string.lower(p.DisplayName),1,#q)==q then return p end end end
local function build()
 for _,o in ipairs(workspace:GetChildren())do if string.sub(o.Name,1,11)=="BBYA Visual" or o.Name=="BBYA Social Systems" then o:Destroy()end end
 local f=Instance.new("Folder");f.Name="BBYA Visual v1.1";f.Parent=workspace
 local systems=Instance.new("Folder");systems.Name="BBYA Social Systems";systems.Parent=workspace
 for _,o in ipairs(workspace:GetDescendants())do if o:IsA("BasePart") then local ln=string.lower(o.Name);if string.find(ln,"stair")then o.Material=Enum.Material.Metal;o.Color=Color3.fromRGB(38,35,47)end;if (string.find(ln,"pillar")or string.find(ln,"column")or string.find(ln,"support")or string.find(ln,"post"))and o.Size.Y>=6 and o.Size.X<=4 and o.Size.Z<=4 then for _,pn in ipairs({"Left VIP Platform","Right VIP Platform"})do local vp=workspace:FindFirstChild(pn);if vp then local lp=vp.CFrame:PointToObjectSpace(o.Position);if math.abs(lp.X)<12 and lp.Z>3 and lp.Z<13 then o.Transparency=1;o.CanCollide=false;o.CanTouch=false;o.CanQuery=false end end end end end end
 local floor=workspace:FindFirstChild("Main Floor");if floor then floor.Material=Enum.Material.Slate;floor.Color=Color3.fromRGB(26,25,33)end
 local dance=workspace:FindFirstChild("Dance Floor");if dance then dance.Material=Enum.Material.Glass;dance.Color=Color3.fromRGB(25,15,38);dance.Reflectance=.12;for i=-2,2 do for j=-2,2 do local tile=part(f,"Reactive Dance Tile",Vector3.new(6,.18,6),dance.CFrame*CFrame.new(i*6,dance.Size.Y/2+.12,j*6),COLORS[((i+j+20)%#COLORS)+1],Enum.Material.Neon,.12,false);task.spawn(function()while tile.Parent do TweenService:Create(tile,TweenInfo.new(.7,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut),{Transparency=.55}):Play();task.wait(.7);TweenService:Create(tile,TweenInfo.new(.7),{Transparency=.1}):Play();task.wait(.7)end end)end end end
 for _,z in ipairs({-40,-12,16,44})do part(f,"Ceiling Beam "..z,Vector3.new(112,.5,1),CFrame.new(0,18.8,z),Color3.fromRGB(25,22,33),Enum.Material.Metal);part(f,"Ceiling Neon "..z,Vector3.new(72,.14,.2),CFrame.new(0,18.42,z),COLORS[(math.floor((z+40)/28)%#COLORS)+1],Enum.Material.Neon,0,false)end
 local arch=workspace:FindFirstChild("Entrance Arch Top");if arch then sign(f,"Entrance Sign",arch.CFrame*CFrame.new(0,2.7,-2.2),"BBYA SOCIAL HUB",24)end
 local booth=workspace:FindFirstChild("DJ Booth");if booth then sign(f,"DJ Sign",booth.CFrame*CFrame.new(0,3,-3.2),"DJ • BBYA 24/7",17);local dj=part(systems,"DJ Console",Vector3.new(8,1,3),booth.CFrame*CFrame.new(0,2,-1),Color3.fromRGB(35,25,48),Enum.Material.Metal);local pr=prompt(dj,"Hype Crowd","DJ Console",.3);pr.Triggered:Connect(function(plr)for _,p in ipairs(f:GetChildren())do if p:IsA("BasePart")and string.find(p.Name,"Neon")then p.Color=COLORS[math.random(1,#COLORS)]end end end)end
 for _,cfg in ipairs({{"Left VIP Platform",Color3.fromRGB(78,30,92)},{"Right VIP Platform",Color3.fromRGB(42,43,100)}})do local p=workspace:FindFirstChild(cfg[1]);if p then sofa(f,cfg[1].." Sofa",p.CFrame*CFrame.new(0,4,8),cfg[2]);part(f,cfg[1].." Table",Vector3.new(7,1.2,5),p.CFrame*CFrame.new(0,4,-2),Color3.fromRGB(30,25,38),Enum.Material.Glass);sign(f,cfg[1].." Sign",p.CFrame*CFrame.new(0,8,13),"VIP LOUNGE",12)end end
 for _,x in ipairs({-44,44})do part(f,"Upper Guard Neon "..x,Vector3.new(.12,.14,64),CFrame.new(x,16.55,-5),x<0 and COLORS[1]or COLORS[3],Enum.Material.Neon,0,false)end
 -- BAR / CAFE social counter
 local bar=part(f,"BBYA Bar",Vector3.new(24,4,6),CFrame.new(-31,3,30),Color3.fromRGB(32,22,38),Enum.Material.Marble);sign(f,"Bar Sign",CFrame.new(-31,7,27),"BBYA BAR • MOCKTAILS",20);local bp=prompt(bar,"Order","BBYA Mocktail Bar",.2);bp.Triggered:Connect(function(plr)local ch=plr.Character;if not ch then return end;local tool=Instance.new("Tool");tool.Name="BBYA Neon Drink";tool.RequiresHandle=true;local h=part(tool,"Handle",Vector3.new(1.2,1.8,1.2),CFrame.new(),COLORS[math.random(1,#COLORS)],Enum.Material.Neon,0,false);h.Anchored=false;h.CanCollide=false;tool.Parent=plr.Backpack end)
 -- PHOTO / SELFIE SPOT
 local photo=part(f,"Photo Wall",Vector3.new(20,12,1),CFrame.new(31,7,31),Color3.fromRGB(45,15,55),Enum.Material.SmoothPlastic);text(photo,"BBYA ♥ NIGHT");for _,x in ipairs({-8,8})do part(f,"Photo Neon "..x,Vector3.new(.25,11,.25),photo.CFrame*CFrame.new(x,0,-.6),COLORS[x<0 and 1 or 3],Enum.Material.Neon,0,false)end
 -- HANGOUT FIRE / chill circle
 local chill=part(f,"Chill Table",Vector3.new(7,1,7),CFrame.new(31,2,-30),Color3.fromRGB(35,30,45),Enum.Material.Glass);sign(f,"Chill Sign",CFrame.new(31,6,-34),"CHILL & TALK",14);for i=0,5 do local a=i*math.pi/3;local s=Instance.new("Seat");s.Name="Chill Seat";s.Size=Vector3.new(4,1.2,4);s.CFrame=CFrame.new(31+math.cos(a)*8,2,-30+math.sin(a)*8)*CFrame.Angles(0,-a+math.pi/2,0);s.Anchored=true;s.Color=Color3.fromRGB(70,35,80);s.Material=Enum.Material.Fabric;s.Parent=f end
 -- ROOFTOP POOL + QUEEN + pool seating
 local pool=workspace:FindFirstChild("Rooftop Pool");if pool then part(f,"Pool Deck",Vector3.new(pool.Size.X+12,.45,pool.Size.Z+12),pool.CFrame*CFrame.new(0,-.8,0),Color3.fromRGB(66,58,68),Enum.Material.WoodPlanks);sign(f,"Pool Sign",pool.CFrame*CFrame.new(0,5,-pool.Size.Z/2-4),"ROOFTOP POOL PARTY",20);for _,x in ipairs({-14,14})do sofa(f,"Pool Sofa "..x,pool.CFrame*CFrame.new(x,2,pool.Size.Z/2+6),Color3.fromRGB(60,35,75))end end
 local lounge=workspace:FindFirstChild("Rooftop Lounge");if lounge then sofa(f,"Roof Sofa",lounge.CFrame*CFrame.new(-10,3,3),Color3.fromRGB(85,35,90));local throne=Instance.new("Seat");throne.Name="BBYA Queen Throne";throne.Size=Vector3.new(5,2.4,5);throne.CFrame=lounge.CFrame*CFrame.new(11,3,3);throne.Anchored=true;throne.Color=Color3.fromRGB(255,190,70);throne.Material=Enum.Material.Metal;throne.Parent=f;part(f,"Queen Throne Back",Vector3.new(5,7,1),throne.CFrame*CFrame.new(0,3,2),Color3.fromRGB(105,30,105),Enum.Material.Fabric);sign(f,"Queen Crown Sign",throne.CFrame*CFrame.new(0,7,2.7),"QUEEN BBYA",10)end
 -- TELEPORT HUB
 local spots={{"DANCE",CFrame.new(0,1,0)},{"VIP",CFrame.new(-30,5,8)},{"BAR",CFrame.new(-31,5,24)},{"PHOTO",CFrame.new(31,5,25)},{"CHILL",CFrame.new(31,4,-30)}}
 for i,v in ipairs(spots)do local pad=part(systems,"Teleport "..v[1],Vector3.new(7,.35,7),CFrame.new(-20+(i-1)*10,1,-44),COLORS[((i-1)%#COLORS)+1],Enum.Material.Neon,.1);local pr=prompt(pad,"Go","Teleport: "..v[1]);pr.Triggered:Connect(function(plr)if plr.Character then plr.Character:PivotTo(v[2]*CFrame.new(0,3,0))end end)end
 -- DAILY VISIT + SOCIAL LEVEL attributes
end
local function night()Lighting.ClockTime=21.5;Lighting.Brightness=2.85;Lighting.ExposureCompensation=.5;Lighting.Ambient=Color3.fromRGB(72,55,84);Lighting.OutdoorAmbient=Color3.fromRGB(40,44,68)end
local function queenTag(c)local h=c:FindFirstChild("Head")or c:WaitForChild("Head",10);if not h or h:FindFirstChild("BBYAQueenTag")then return end;local g=Instance.new("BillboardGui");g.Name="BBYAQueenTag";g.Size=UDim2.fromOffset(150,34);g.StudsOffset=Vector3.new(0,3,0);g.MaxDistance=45;g.Parent=h;local t=Instance.new("TextLabel");t.BackgroundTransparency=1;t.Size=UDim2.fromScale(1,1);t.Text="👑 RATU BBYA";t.Font=Enum.Font.GothamBold;t.TextColor3=Color3.fromRGB(255,220,90);t.TextScaled=true;t.Parent=g end
local function queenCommand(p,msg)if p.UserId~=BBYA_QUEEN_USER_ID or string.sub(msg,1,1)~="!"then return end;local a=string.split(msg," ");local c=string.lower(a[1]);if c=="!kick"then local t=findPlayer(a[2]);if t and t~=p then t:Kick("Removed by BBYA Queen")end elseif c=="!bring"then local t=findPlayer(a[2]);if t and t.Character and p.Character then t.Character:PivotTo(p.Character:GetPivot()*CFrame.new(3,0,0))end elseif c=="!goto"then local t=findPlayer(a[2]);if t and t.Character and p.Character then p.Character:PivotTo(t.Character:GetPivot()*CFrame.new(3,0,0))end elseif c=="!speed"then local h=p.Character and p.Character:FindFirstChildOfClass("Humanoid");if h then h.WalkSpeed=math.clamp(tonumber(a[2])or 32,16,80)end elseif c=="!normal"then local h=p.Character and p.Character:FindFirstChildOfClass("Humanoid");if h then h.WalkSpeed=16 end elseif c=="!day"then Lighting.ClockTime=14 elseif c=="!night"then night()elseif c=="!party"then for _,o in ipairs(workspace:GetDescendants())do if o:IsA("BasePart")and string.find(o.Name,"Neon")then o.Color=COLORS[math.random(1,#COLORS)]end end end end
local function setup(p)local q=p.UserId==BBYA_QUEEN_USER_ID;p:SetAttribute("BBYARole",q and "BBYA_QUEEN"or"GUEST");p:SetAttribute("BBYAQueen",q);p:SetAttribute("SocialLevel",1);p:SetAttribute("VisitReward",true);if q then p:SetAttribute("IsVIP",true);p:SetAttribute("BBYAAllAccess",true);p.CharacterAdded:Connect(function(c)task.wait(1);queenTag(c)end);p.Chatted:Connect(function(m)queenCommand(p,m)end);if p.Character then queenTag(p.Character)end end end
build();night();Players.PlayerAdded:Connect(setup);for _,p in ipairs(Players:GetPlayers())do setup(p)end
print("[BBYA] v1.1 FULL SOCIAL CLUB PACK loaded: dance, DJ, VIP, bar, photo, chill, pool, teleport, social attributes, Queen controls")