-- BBYAVATAR FPS vertical slice configuration
return {
    Version = "FPS-PROTOTYPE-0.1",
    ScoreLimit = 50,
    RespawnTime = 3,
    Weapons = {
        AR4 = {
            DisplayName = "AR-4 RIFLE",
            Damage = 24,
            HeadMultiplier = 1.65,
            RPM = 690,
            Magazine = 30,
            Reserve = 120,
            ReloadTime = 2.15,
            Range = 650,
            SpreadHip = 1.15,
            SpreadADS = 0.28,
            Recoil = 1.15,
            Auto = true,
            FOV = 74,
            ADSFOV = 58,
        },
        SM9 = {
            DisplayName = "SM-9",
            Damage = 18,
            HeadMultiplier = 1.55,
            RPM = 880,
            Magazine = 35,
            Reserve = 140,
            ReloadTime = 1.9,
            Range = 430,
            SpreadHip = 1.45,
            SpreadADS = 0.45,
            Recoil = 0.85,
            Auto = true,
            FOV = 76,
            ADSFOV = 61,
        },
        DMR7 = {
            DisplayName = "DMR-7",
            Damage = 43,
            HeadMultiplier = 1.8,
            RPM = 310,
            Magazine = 16,
            Reserve = 64,
            ReloadTime = 2.45,
            Range = 900,
            SpreadHip = 1.9,
            SpreadADS = 0.12,
            Recoil = 2.1,
            Auto = false,
            FOV = 72,
            ADSFOV = 48,
        },
        P12 = {
            DisplayName = "P-12",
            Damage = 27,
            HeadMultiplier = 1.7,
            RPM = 420,
            Magazine = 12,
            Reserve = 48,
            ReloadTime = 1.55,
            Range = 350,
            SpreadHip = 1.25,
            SpreadADS = 0.32,
            Recoil = 1.35,
            Auto = false,
            FOV = 74,
            ADSFOV = 60,
        },
    },
    Loadout = {"AR4", "SM9", "DMR7", "P12"},
}
